### ISSUE TITLE
数据库的配置在哪里填写呢？

### ISSUE THREAD

**Issue by git-zjx** [Blackyukun/dingdian#2]
数据库的配置在哪里填写呢？

**Comment by yokonsan** [comment]
`config.py`配置文件的`SQLALCHEMY_DATABASE_URI`变量，默认是`sqlite`，如果配置`mysql`可以将变量设为`mysql+pymysql://root:password@localhost:3306/db`

**Comment by zhangchangrui** [comment]
Try to run this command from the system terminal. Make sure that you use the correct version of 'pip' installed for your Python interpreter located at '/usr/local/bin/python3.6'.
失败

**Comment by git-zjx** [comment]
@zhangchangrui pip和python版本不对应？？

**Comment by yokonsan** [comment]
项目已经很久没有更新了，如果运行失败可以检测是否是网站的爬虫无效。demo 站点由于是免费平台，数据库用完了，所以会报500错误。如果可能，后续会更新项目的

**Comment by git-zjx** [comment]
@Blackyukun 后续可以带我一个不？

**Comment by yokonsan** [comment]
@git-zjx 可以啊，这项目代码现在看着好尴尬，准备重构QAQ~

**Comment by git-zjx** [comment]
@Blackyukun 好，那我就静等消息了

**Comment by dkvirus** [comment]
@Blackyukun 这个项目不错的，继续搞啊。目前首页提供的网站访问已经 500 了。
